# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

long_run_var <- function(A, Q, m, p) {
    .Call('_dateutils_long_run_var', PACKAGE = 'dateutils', A, Q, m, p)
}

Stack_Obs <- function(nn, p, r = 0L) {
    .Call('_dateutils_Stack_Obs', PACKAGE = 'dateutils', nn, p, r)
}

which_date_leq <- function(date, Dvec) {
    .Call('_dateutils_which_date_leq', PACKAGE = 'dateutils', date, Dvec)
}

which_date_geq <- function(date, Dvec) {
    .Call('_dateutils_which_date_geq', PACKAGE = 'dateutils', date, Dvec)
}

which_date_closest <- function(date, Dvec) {
    .Call('_dateutils_which_date_closest', PACKAGE = 'dateutils', date, Dvec)
}

which_date_closest_ordered <- function(FromVec, IndVec) {
    .Call('_dateutils_which_date_closest_ordered', PACKAGE = 'dateutils', FromVec, IndVec)
}

Day <- function(dte) {
    .Call('_dateutils_Day', PACKAGE = 'dateutils', dte)
}

replace_day <- function(date, new_day) {
    .Call('_dateutils_replace_day', PACKAGE = 'dateutils', date, new_day)
}

MonthDays <- function(year, month) {
    .Call('_dateutils_MonthDays', PACKAGE = 'dateutils', year, month)
}

End_of_Month <- function(date) {
    .Call('_dateutils_End_of_Month', PACKAGE = 'dateutils', date)
}

End_next_Month <- function(date) {
    .Call('_dateutils_End_next_Month', PACKAGE = 'dateutils', date)
}

End_previous_Month <- function(date) {
    .Call('_dateutils_End_previous_Month', PACKAGE = 'dateutils', date)
}

End_of_Quarter <- function(date) {
    .Call('_dateutils_End_of_Quarter', PACKAGE = 'dateutils', date)
}

First_previous_Quarter <- function(date) {
    .Call('_dateutils_First_previous_Quarter', PACKAGE = 'dateutils', date)
}

first_of_quarter <- function(date) {
    .Call('_dateutils_first_of_quarter', PACKAGE = 'dateutils', date)
}

end_of_year <- function(date) {
    .Call('_dateutils_end_of_year', PACKAGE = 'dateutils', date)
}

