# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Comp_Form <- function(B) {
    .Call(`_dateutils_Comp_Form`, B)
}

Long_Run_Var <- function(A, Q, m, p) {
    .Call(`_dateutils_Long_Run_Var`, A, Q, m, p)
}

finite_cols <- function(X) {
    .Call(`_dateutils_finite_cols`, X)
}

count_finite <- function(X) {
    .Call(`_dateutils_count_finite`, X)
}

any_obs_cols <- function(X) {
    .Call(`_dateutils_any_obs_cols`, X)
}

Stack_Obs <- function(nn, p, r = 0L) {
    .Call(`_dateutils_Stack_Obs`, nn, p, r)
}

which_date_leq <- function(date, Dvec) {
    .Call(`_dateutils_which_date_leq`, date, Dvec)
}

which_date_geq <- function(date, Dvec) {
    .Call(`_dateutils_which_date_geq`, date, Dvec)
}

which_date_closest <- function(date, Dvec) {
    .Call(`_dateutils_which_date_closest`, date, Dvec)
}

which_date_closest_ordered <- function(FromVec, IndVec) {
    .Call(`_dateutils_which_date_closest_ordered`, FromVec, IndVec)
}

Day <- function(dte) {
    .Call(`_dateutils_Day`, dte)
}

replace_day <- function(date, new_day) {
    .Call(`_dateutils_replace_day`, date, new_day)
}

MonthDays <- function(year, month) {
    .Call(`_dateutils_MonthDays`, year, month)
}

End_of_Month <- function(date, shift = 0L) {
    .Call(`_dateutils_End_of_Month`, date, shift)
}

End_next_Month <- function(date) {
    .Call(`_dateutils_End_next_Month`, date)
}

End_previous_Month <- function(date) {
    .Call(`_dateutils_End_previous_Month`, date)
}

End_of_Quarter <- function(date, shift = 0L) {
    .Call(`_dateutils_End_of_Quarter`, date, shift)
}

First_previous_Quarter <- function(date) {
    .Call(`_dateutils_First_previous_Quarter`, date)
}

End_previous_Quarter <- function(date) {
    .Call(`_dateutils_End_previous_Quarter`, date)
}

First_Of_Quarter <- function(date) {
    .Call(`_dateutils_First_Of_Quarter`, date)
}

End_Of_Year <- function(date) {
    .Call(`_dateutils_End_Of_Year`, date)
}

NumDum <- function(x) {
    .Call(`_dateutils_NumDum`, x)
}

Fill_Forward <- function(x) {
    .Call(`_dateutils_Fill_Forward`, x)
}

rollmean_cpp <- function(x, n) {
    .Call(`_dateutils_rollmean_cpp`, x, n)
}

RollMax <- function(x, n) {
    .Call(`_dateutils_RollMax`, x, n)
}

RollMin <- function(x, n) {
    .Call(`_dateutils_RollMin`, x, n)
}

